{% set name = "django-controlcenter" %}
{% set version = "0.3.0" %}
{% set sha256 = "50e24e1b372131a5a89cf952c504775fab7f53cda78d8911c2e4f637ed7b7cba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/byashimov/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - django >=1.8
    - django-pkgconf

test:
  imports:
    - controlcenter
    - controlcenter.templatetags
    - controlcenter.widgets

about:
  home: https://github.com/byashimov/django-controlcenter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Set of widgets to build dashboards for Django projects
  description: Set of widgets to build dashboards for Django projects
  doc_url: http://django-controlcenter.readthedocs.io/en/stable/
  dev_url: https://github.com/byashimov/django-controlcenter

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
