{% set name = "django-controlcenter" %}
{% set version = "0.2.7" %}
{% set sha256 = "96497230199585ddd9e72d449cfd2acc444f8590af8463d36e9fce471abde69d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/byashimov/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - django >=1.8
    - django-pkgconf

test:
  imports:
    - controlcenter
    - controlcenter.templatetags
    - controlcenter.widgets

about:
  home: https://github.com/byashimov/django-controlcenter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Set of widgets to build dashboards for Django projects'
  description: 
    Set of widgets to build dashboards for Django projects
  doc_url: http://django-controlcenter.readthedocs.io/en/stable/
  dev_url: https://github.com/byashimov/django-controlcenter

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
