travis:
  secure:
    BINSTAR_TOKEN: fj/fHdq+7Nw6zCo8Z1GrmVIARTYR8nqdYmzHlym9atbcURbjLQLO1lL43kW0RorH8toJUXfqdZgC+pIqp/U3DXNkjyS4uhk7E49WCLcNGsZiRkqnq/vDPfZRGu28EplqwEZiwvSCSeR0gtnw2rVwQiVHtPz24YNC6sxKIGTQQwbQszpQgCee6oWBZv2qmHdV9Ka7Rx7abC4BydYCTYD6scjKUVl5nHCxPTcLNPO3uaTFHkPaF4jxnkXGUubIW0zLXOUpe/nIB7f+jLAtgJMipcMqEmWKRF4aFN3sRpypelfauV0O4EUTpaQNjMrIncum9QhF8TG05l0T6jxzlQnFVzQm1vNF4W9lLBxmC9yPvLdn35gV3TZvtu3xLdw115myfdZXIxBIErpiSJJFDMhaavrXQOdtBc0ZezqTRHk8NpsEkolYjcPr6/055lxI5PiWWSSXF+6db/j3k0dQsNr7tKEtomLgp48dADaMqe9FxRKBv5m9HLXYWhfz0sB56PTrChRzXvduoNEpVipdCQyzX3I4ndf+6f8XPaoj7aVvDlM3HqM3ah1ClujrCDU3d67dH36LcWT4KHHtUmcpsEmWR2c8LgK9NIwpZKtLsos7ksdYb7uonIF4pEHaCu05s/1vzPC1Jnj+l3CxyQ1kdzQdn2iiE7JxFUk1qU80TfrqcvI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
