travis:
  secure:
    BINSTAR_TOKEN: IB++sGMhtDu4sBIzIFGwf1PX8BR86RmRhLeLoqgxLPrUFkw7FfPLthj8zSBnVXDOFm4RmGZ7Y/XoUfM+PHNpiatGkCKmQPaCALoD89GdU1dLreRDhzY4VExqHHYddp27wXwkvnmE2Uy7ii8FZ3DBVZ3OfFm9yozmfTVjpYgOdTV6fsAVYwDWxkCgPgS1giJPga4W7NPfVDL3vrSECoWDTE+BIdZRMwFFTQPF9wA5Vw3726aDa2bTt7wl8H9Lnn9ixPdFyhHc8GaCgBjounNOEv5GZKYX2MQlSqS0N29dSVjSce//szUkkoNTDfJZXm+YeKozQ8gZ7EBUJ5+3DQCRvRlajskudKGqBIaFL+M/kg5Pc2P4LSohF2q9enLdQ5xxxM2ByToUj//MTfIwnhd1Re5svO1ViL2Sc/sD31JrjRmvlps4pQcxSKxGNM/ZlrUQsnOgkZr59bfg9DuNkShrZpVzgH8LzsPJpaPNpN6Qjv3P++K8Ns0wxtMYNsf6dQdu88U6b9obtRWIkRXvkJD3+ETwdF+EOBl7BqeneIZNaRrMiXspkoE5wRRIYuI9DMxLLix93Ivxua+V7dLtD4Dl5K+qNzm1gvLEXwsFr7l9kKtDQpAgYBIMpMwcMHp0wNACDF3omhh6pldLIduekxK4sxby7Om+ou4ND2dJsEa3KHE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
